import supabase from "./supabase"

export const sendBibleBooks = async () => {
  return "Already sent Bible books."

  const { data, error } = await supabase.from("bible_book").insert([
    { name: 'Gênesis', testament: 'Velho', chapters: 50 },
    { name: 'Êxodo', testament: 'Velho', chapters: 40 },
    { name: 'Levítico', testament: 'Velho', chapters: 27 },
    { name: 'Números', testament: 'Velho', chapters: 36 },
    { name: 'Deuteronômio', testament: 'Velho', chapters: 34 },
    { name: 'Josué', testament: 'Velho', chapters: 24 },
    { name: 'Juízes', testament: 'Velho', chapters: 21 },
    { name: 'Rute', testament: 'Velho', chapters: 4 },
    { name: '1 Samuel', testament: 'Velho', chapters: 31 },
    { name: '2 Samuel', testament: 'Velho', chapters: 24 },
    { name: '1 Reis', testament: 'Velho', chapters: 22 },
    { name: '2 Reis', testament: 'Velho', chapters: 25 },
    { name: '1 Crônicas', testament: 'Velho', chapters: 29 },
    { name: '2 Crônicas', testament: 'Velho', chapters: 36 },
    { name: 'Esdras', testament: 'Velho', chapters: 10 },
    { name: 'Neemias', testament: 'Velho', chapters: 13 },
    { name: 'Ester', testament: 'Velho', chapters: 10 },
    { name: 'Jó', testament: 'Velho', chapters: 42 },
    { name: 'Salmos', testament: 'Velho', chapters: 150 },
    { name: 'Provérbios', testament: 'Velho', chapters: 31 },
    { name: 'Eclesiastes', testament: 'Velho', chapters: 12 },
    { name: 'Cânticos', testament: 'Velho', chapters: 8 },
    { name: 'Isaías', testament: 'Velho', chapters: 66 },
    { name: 'Jeremias', testament: 'Velho', chapters: 52 },
    { name: 'Lamentações', testament: 'Velho', chapters: 5 },
    { name: 'Ezequiel', testament: 'Velho', chapters: 48 },
    { name: 'Daniel', testament: 'Velho', chapters: 12 },
    { name: 'Oseias', testament: 'Velho', chapters: 14 },
    { name: 'Joel', testament: 'Velho', chapters: 3 },
    { name: 'Amós', testament: 'Velho', chapters: 9 },
    { name: 'Obadias', testament: 'Velho', chapters: 1 },
    { name: 'Jonas', testament: 'Velho', chapters: 4 },
    { name: 'Miqueias', testament: 'Velho', chapters: 7 },
    { name: 'Naum', testament: 'Velho', chapters: 3 },
    { name: 'Habacuque', testament: 'Velho', chapters: 3 },
    { name: 'Sofonias', testament: 'Velho', chapters: 3 },
    { name: 'Ageu', testament: 'Velho', chapters: 2 },
    { name: 'Zacarias', testament: 'Velho', chapters: 14 },
    { name: 'Malaquias', testament: 'Velho', chapters: 4 },
    { name: 'Mateus', testament: 'Novo', chapters: 28 },
    { name: 'Marcos', testament: 'Novo', chapters: 16 },
    { name: 'Lucas', testament: 'Novo', chapters: 24 },
    { name: 'João', testament: 'Novo', chapters: 21 },
    { name: 'Atos', testament: 'Novo', chapters: 28 },
    { name: 'Romanos', testament: 'Novo', chapters: 16 },
    { name: '1 Coríntios', testament: 'Novo', chapters: 16 },
    { name: '2 Coríntios', testament: 'Novo', chapters: 13 },
    { name: 'Gálatas', testament: 'Novo', chapters: 6 },
    { name: 'Efésios', testament: 'Novo', chapters: 6 },
    { name: 'Filipenses', testament: 'Novo', chapters: 4 },
    { name: 'Colossenses', testament: 'Novo', chapters: 4 },
    { name: '1 Tessalonicenses', testament: 'Novo', chapters: 5 },
    { name: '2 Tessalonicenses', testament: 'Novo', chapters: 3 },
    { name: '1 Timóteo', testament: 'Novo', chapters: 6 },
    { name: '2 Timóteo', testament: 'Novo', chapters: 4 },
    { name: 'Tito', testament: 'Novo', chapters: 3 },
    { name: 'Filemon', testament: 'Novo', chapters: 1 },
    { name: 'Hebreus', testament: 'Novo', chapters: 13 },
    { name: 'Tiago', testament: 'Novo', chapters: 5 },
    { name: '1 Pedro', testament: 'Novo', chapters: 5 },
    { name: '2 Pedro', testament: 'Novo', chapters: 3 },
    { name: '1 João', testament: 'Novo', chapters: 5 },
    { name: '2 João', testament: 'Novo', chapters: 1 },
    { name: '3 João', testament: 'Novo', chapters: 1 },
    { name: 'Judas', testament: 'Novo', chapters: 1 },
    { name: 'Apocalipse', testament: 'Novo', chapters: 22 },
  ])

  console.log(data, error)

  if (error)
    alert("Deu algum erro no banco de dados")
}